from alembic import op


revision = "20260426_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR(255) NOT NULL,
            password_hash VARCHAR(255) NOT NULL,
            is_active BOOLEAN NOT NULL,
            activation_key VARCHAR(64),
            activation_key_expires TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_activation_key ON users (activation_key)")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS virtual_machines (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(128) NOT NULL,
            host VARCHAR(255) NOT NULL,
            port INTEGER NOT NULL,
            protocol VARCHAR(16) NOT NULL,
            is_active BOOLEAN NOT NULL,
            current_user_id INTEGER REFERENCES users (id),
            last_used_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_virtual_machines_id ON virtual_machines (id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_virtual_machines_name ON virtual_machines (name)")

    op.execute(
        """
        INSERT INTO virtual_machines (name, host, port, protocol, is_active)
        VALUES
            ('proxy-1', '127.0.0.1', 1080, 'socks5', TRUE),
            ('proxy-2', '127.0.0.1', 1081, 'socks5', TRUE),
            ('proxy-3', '127.0.0.1', 8080, 'http', TRUE)
        ON CONFLICT (name) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS virtual_machines")
    op.execute("DROP TABLE IF EXISTS users")
